2019-01-05 00:13:30,534 INFO: CardiacBook startup [in /home/ubuntu/cardiacpedia/cardiacpedia/__init__.py:52]
2019-01-05 00:13:56,655 ERROR: Exception on /devices/compatibility [GET] [in /home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/flask_user/decorators.py", line 58, in decorator
    return view_function(*args, **kwargs)
  File "/home/ubuntu/cardiacpedia/cardiacpedia/devices/views.py", line 45, in compatibility
    return render_template('/Devices/Change/compatible.html', page_title="Upgrade / PAC Change", form=form, form_type=form_type)
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ubuntu/cardiacpedia/venv/lib/python3.5/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /Devices/Change/compatible.html
2019-01-04 22:08:14,268 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-04 22:08:19,367 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-04 23:09:36,487 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-04 23:09:38,935 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-05 08:50:15,546 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-05 08:50:17,443 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-05 09:38:47,816 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-05 09:40:22,765 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-05 09:43:02,402 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-05 09:43:34,753 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-05 09:43:42,375 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-05 09:46:06,132 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-05 09:48:43,050 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-05 09:48:44,912 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
2019-01-05 09:53:09,598 INFO: CardiacBook startup [in C:\Users\farbo\Desktop\CardiacPedia\cardiacpedia\__init__.py:52]
